[workspace]
types = "../scripts/types"

[features]
seeds = false
skip-lint = false
[programs.localnet]
token_swap = "suobUdMc9nSaQ1TjRkQA4K6CR9CmDiU9QViN7kVw74T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/daniel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
