[workspace]
types = "scripts/types"

[features]
seeds = false
skip-lint = false
[programs.localnet]
token_swap = "sutsaKhPL3nMSPtvRY3e9MbpmqQbEJip6vYqT9AQcgN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/daniel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
