[workspace]
types = "../scripts/types"

[features]
seeds = false
skip-lint = false
[programs.localnet]
token_swap = "suobUdMc9nSaQ1TjRkQA4K6CR9CmDiU9QViN7kVw74T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
rpc_port = 8890
faucet_port = 9900

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 token-swap/tests/token-swap.ts"
